feat: build source

diff --git a/.circleci/config-sample.yml b/.circleci/config-sample.yml
--- a/.circleci/config-sample.yml
+++ b/.circleci/config-sample.yml
@@ -4,7 +4,7 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here
+      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
@@ -16,7 +16,7 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
@@ -24,14 +24,14 @@ commands:
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
             SUCCESS = 1
-            if(( $SUCCESS==1 ));
+            if(( $SUCCESS==1 )); 
             then
             #  cd ~/project/backend
             #  npm install
             #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
-
+            
 jobs:
   build-frontend:
     docker:
@@ -43,10 +43,8 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            cd ~/project/frontend
-            npm install
-            npm run build
-            # exit 1
+            # Your code here
+            exit 1
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -61,9 +59,8 @@ jobs:
       - run:
           name: Back-end build
           command: |
-            cd ~/project/backend
-            npm install
-            npm run build
+             # Your code here
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -75,7 +72,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-
+                
   test-backend:
     docker:
       # Docker image here
@@ -83,7 +80,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-
+            
   scan-frontend:
     docker:
       # Docker image here
@@ -112,7 +109,7 @@ jobs:
               --template-file .circleci/files/backend.yml \
               #--tags project=your-tag \
               # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"
+              # --parameter-overrides ID="your workflow id"  
               exit 1
       - run:
           name: Ensure front-end infrastructure exist
@@ -121,7 +118,7 @@ jobs:
               --template-file .circleci/files/frontend.yml \
               #--tags project=your-tag \
               # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"
+              # --parameter-overrides ID="your workflow id"  
               exit 1
       - run:
           name: Add back-end ip to ansible inventory
@@ -132,7 +129,7 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     docker:
@@ -151,7 +148,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
@@ -168,7 +165,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-     # Here's where you will add some code to rollback on failure
+     # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
@@ -189,8 +186,8 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
-
+      # Here's where you will add some code to rollback on failure      
+                    
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
@@ -206,11 +203,11 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
-      # Lightweight Docker image
+      # Lightweight Docker image 
     steps:
       # Checkout code from git
       - run:
@@ -229,7 +226,7 @@ jobs:
           name: Frontend smoke test.
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
@@ -244,7 +241,7 @@ jobs:
           name: Update cloudfront distribution
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
 cleanup:
     docker:
@@ -264,7 +261,7 @@ cleanup:
             then
               # your code here
             fi
-
+            
 
 workflows:
   default:
